# Generated by Django 4.2.6 on 2023-10-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('will_attend', models.BooleanField()),
                ('both_attending', models.BooleanField()),
                ('dietary_requirements', models.CharField(max_length=255)),
                ('attending_day2', models.BooleanField()),
                ('other_dietary_requirements', models.CharField(max_length=255)),
            ],
        ),
    ]
