# Generated by Django 4.2.6 on 2023-10-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='other_dietary_requirements',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='music_requests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='other_dietary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='attending_day2',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='both_attending',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='dietary_requirements',
            field=models.CharField(blank=True, choices=[('Coeliac', 'Coeliac'), ('Lactose', 'Lactose Intolerant'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='will_attend',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
