# Generated by Django 4.2.6 on 2023-10-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_remove_rsvp_other_dietary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='dietary_requirements',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
