# Generated by Django 4.2.6 on 2023-10-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0005_alter_rsvp_dietary_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='dietary_requirements',
            field=models.CharField(choices=[('Coeliac', 'Coeliac'), ('Lactose', 'Lactose Intolerant'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
