# Generated by Django 4.2.6 on 2023-10-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0006_alter_rsvp_dietary_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='other_dietary_input',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
