# Generated by Django 4.2.6 on 2023-10-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0007_rsvp_other_dietary_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='music_requests',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='other_dietary_input',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
