# Generated by Django 4.2.6 on 2023-10-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0008_alter_rsvp_music_requests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='dietary_requirements',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='dietary_requirements',
            field=models.ManyToManyField(blank=True, to='rsvp.dietaryrequirement'),
        ),
    ]
