# Generated by Django 4.2.6 on 2023-10-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0013_rsvp_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
