# Generated by Django 4.2.6 on 2023-10-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0015_rsvp_not_attending_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='both_attending',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='not_attending_guest',
        ),
        migrations.AlterField(
            model_name='dietaryrequirement',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='attending_day2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', "I'll see how the head is")], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='music_requests',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.guestname'),
        ),
    ]
