# Generated by Django 4.2.6 on 2023-10-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0017_remove_rsvp_name_remove_rsvp_will_attend_rsvp_name1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='attending_day2',
            new_name='attending_day21',
        ),
        migrations.RenameField(
            model_name='rsvp',
            old_name='other_dietary_input',
            new_name='other_dietary_input1',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='dietary_requirements',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='attending_day22',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', "I'll see how the head is")], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='attending_day23',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', "I'll see how the head is")], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='attending_day24',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', "I'll see how the head is")], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='dietary_requirements1',
            field=models.ManyToManyField(blank=True, related_name='dietary1_rsvp', to='rsvp.dietaryrequirement'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='dietary_requirements2',
            field=models.ManyToManyField(blank=True, related_name='dietary2_rsvp', to='rsvp.dietaryrequirement'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='dietary_requirements3',
            field=models.ManyToManyField(blank=True, related_name='dietary3_rsvp', to='rsvp.dietaryrequirement'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='dietary_requirements4',
            field=models.ManyToManyField(blank=True, related_name='dietary4_rsvp', to='rsvp.dietaryrequirement'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='other_dietary_input2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='other_dietary_input3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='other_dietary_input4',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
