# Generated by Django 4.2.6 on 2023-10-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0019_rename_attending_day21_rsvp_attending_day2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='attending_day2',
            new_name='attending_day2_1',
        ),
        migrations.RenameField(
            model_name='rsvp',
            old_name='other_dietary_input',
            new_name='other_dietary_input_1',
        ),
        migrations.RenameField(
            model_name='rsvp',
            old_name='will_attend1',
            new_name='will_attend_1',
        ),
        migrations.RenameField(
            model_name='rsvp',
            old_name='will_attend2',
            new_name='will_attend_2',
        ),
        migrations.RenameField(
            model_name='rsvp',
            old_name='will_attend3',
            new_name='will_attend_3',
        ),
        migrations.RenameField(
            model_name='rsvp',
            old_name='will_attend4',
            new_name='will_attend_4',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='dietary_requirements',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='name4',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='attending_day2_2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', "I'll see how the head is")], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='attending_day2_3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', "I'll see how the head is")], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='attending_day2_4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', "I'll see how the head is")], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='dietary_requirements_1',
            field=models.ManyToManyField(blank=True, related_name='rsvps_dietary_1', to='rsvp.dietaryrequirement'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='dietary_requirements_2',
            field=models.ManyToManyField(blank=True, related_name='rsvps_dietary_2', to='rsvp.dietaryrequirement'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='dietary_requirements_3',
            field=models.ManyToManyField(blank=True, related_name='rsvps_dietary_3', to='rsvp.dietaryrequirement'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='dietary_requirements_4',
            field=models.ManyToManyField(blank=True, related_name='rsvps_dietary_4', to='rsvp.dietaryrequirement'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='name_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps_name1', to='rsvp.guestname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='name_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps_name2', to='rsvp.guestname'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='name_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps_name3', to='rsvp.guestname'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='name_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps_name4', to='rsvp.guestname'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='other_dietary_input_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='other_dietary_input_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='other_dietary_input_4',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
