# Generated by Django 4.2.6 on 2023-10-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0020_rename_attending_day2_rsvp_attending_day2_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='name_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='name_2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='name_3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='name_4',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GuestName',
        ),
    ]
