# Generated by Django 4.2.6 on 2023-10-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0021_alter_rsvp_name_1_alter_rsvp_name_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='attending_day2_5',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', "I'll see how the head is")], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='dietary_requirements_5',
            field=models.ManyToManyField(blank=True, related_name='rsvps_dietary_5', to='rsvp.dietaryrequirement'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='name_5',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='other_dietary_input_5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='will_attend_5',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are you attending?'),
        ),
    ]
